openapi: 3.0.0
info:
  title: Sample API
  description: "Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/)\
    \ or HTML."
  version: 0.1.9
servers:
- url: /
paths:
  /users:
    get:
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      operationId: users_get
      responses:
        "200":
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                x-content-type: application/json
      x-openapi-router-controller: swagger_server.controllers.default_controller
    post:
      summary: Creates a user.
      operationId: users_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        "201":
          description: Created
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /users/{userId}:
    get:
      summary: Returns a user by ID.
      operationId: users_user_id_get
      parameters:
      - name: userId
        in: path
        description: Parameter description in CommonMark or HTML.
        required: true
        style: simple
        explode: false
        schema:
          minimum: 1
          type: integer
          format: int64
      responses:
        "200":
          description: A user object.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        "400":
          description: The specified user ID is invalid (not a number).
        "404":
          description: A user with the specified ID was not found.
        default:
          description: Unexpected error
      x-openapi-router-controller: swagger_server.controllers.default_controller
components:
  schemas:
    User:
      required:
      - id
      - name
      properties:
        id:
          type: integer
        name:
          type: string
      example:
        name: name
        id: 0

